### ISSUE TITLE
error under "Svelte DevTools"

### ISSUE THREAD

**Issue by vfilatov** [bestguy/sveltestrap#127] opened 2020-02-18 20:02 UTC
While trying 1st sample from https://bestguy.github.io/sveltestrap/?path=/story/components--navbar
under "Svelte DevTools" (https://chrome.google.com/webstore/detail/svelte-devtools/ckolcbmkjpjmangdbmnkpjigpkddpogn?hl=en-US)
I get the error below on console.
```
<script>
  import {
    Collapse,
    Navbar,
    NavbarToggler,
    NavbarBrand,
    Nav,
    NavItem,
    NavLink,
    UncontrolledDropdown,
    DropdownToggle,
    DropdownMenu,
    DropdownItem
  } from 'sveltestrap';

  let isOpen = false;

  function handleUpdate(event) {
    isOpen = event.detail.isOpen;
  }
</script>

<Navbar color="light" light expand="md">
  <NavbarBrand href="/">sveltestrap</NavbarBrand>
  <NavbarToggler on:click={() => (isOpen = !isOpen)} />
  <Collapse {isOpen} navbar expand="md" on:update={handleUpdate}>
    <Nav class="ml-auto" navbar>
      <NavItem>
        <NavLink href="#components/">Components</NavLink>
      </NavItem>
      <NavItem>
        <NavLink href="https://github.com/bestguy/sveltestrap">GitHub</NavLink>
      </NavItem>
      <UncontrolledDropdown nav inNavbar>
        <DropdownToggle nav caret>Options</DropdownToggle>
        <DropdownMenu right>
          <DropdownItem>Option 1</DropdownItem>
          <DropdownItem>Option 2</DropdownItem>
          <DropdownItem divider />
          <DropdownItem>Reset</DropdownItem>
        </DropdownMenu>
      </UncontrolledDropdown>
    </Nav>
  </Collapse>
</Navbar>

VM997:644 Uncaught DOMException: Failed to execute 'postMessage' on 'Window': function fill() { [native code] } could not be cloned.
    at Object.add (<anonymous>:644:14)
    at add (<anonymous>:11:51)
    at addNode (<anonymous>:104:5)
    at Object.block.m (<anonymous>:244:11)
    at mount_component (http://localhost:5000/build/bundle.js:534:30)
    at mount (http://localhost:5000/build/bundle.js:6151:8)
    at updateProfile (<anonymous>:49:7)
    at Object.block.m (<anonymous>:248:9)
    at mount (http://localhost:5000/build/bundle.js:2177:22)
    at updateProfile (<anonymous>:49:7)
```

**Comment by vfilatov** [comment] 2020-02-18 20:04
Checked on

- Chromium: Version 81.0.4033.2 (Developer Build) Ubuntu 19.10 (64-bit)
- Chrome: Version 80.0.3987.116 (Official Build) unknown (64-bit)

**Comment by vfilatov** [comment] 2020-02-18 21:10
On Firefox:

- DataCloneError: The object could not be cloned.

**Comment by bestguy** [comment] 2020-02-19 14:49
Hi @vfilatov,  are you running the sample locally?  Or are you looking at the website docs.
The docs use storybook library which uses React, etc that might confuse things or trigger errors

**Comment by frederikhors** [comment] 2020-02-19 14:59
@bestguy I think we should only accept issue with issue reproduction on REPLs online.

The little time we can devote to FOSS should not be supportive of non-repository problems.

Am I wrong?

**Comment by vfilatov** [comment] 2020-02-19 16:49
No, you are not wrong. but I might be wrong and there is a big change I'm
doing something wrong.
I'm not able to reproduce that on REPLs online.

Here are steps to reproduce the error.

   - npx degit sveltejs/template my-svelte-project
   - cd my-svelte-project/
   - npm i
   - npm i sveltestrap
   - npm i bootstrap
   - cat <<EOF > src/App.svelte

<script>
  import {
    Collapse,
    Navbar,
    NavbarToggler,
    NavbarBrand,
    Nav,
    NavItem,
    NavLink,
    UncontrolledDropdown,
    DropdownToggle,
    DropdownMenu,
    DropdownItem
  } from 'sveltestrap';

  let isOpen = false;

  function handleUpdate(event) {
    isOpen = event.detail.isOpen;
  }
</script>

<Navbar color="light" light expand="md">
  <NavbarBrand href="/">sveltestrap</NavbarBrand>
  <NavbarToggler on:click={() => (isOpen = !isOpen)} />
  <Collapse {isOpen} navbar expand="md" on:update={handleUpdate}>
    <Nav class="ml-auto" navbar>
      <NavItem>
        <NavLink href="#components/">Components</NavLink>
      </NavItem>
      <NavItem>
        <NavLink href="https://github.com/bestguy/sveltestrap
">GitHub</NavLink>
      </NavItem>
      <UncontrolledDropdown nav inNavbar>
        <DropdownToggle nav caret>Options</DropdownToggle>
        <DropdownMenu right>
          <DropdownItem>Option 1</DropdownItem>
          <DropdownItem>Option 2</DropdownItem>
          <DropdownItem divider />
          <DropdownItem>Reset</DropdownItem>
        </DropdownMenu>
      </UncontrolledDropdown>
    </Nav>
  </Collapse>
</Navbar>
EOF

   - npm run dev
   - open browser (chrome/chromium/firefox) I use Ubuntu 19.10
   - open DevTools
   - go to http://localhost:5000

It works, no errors

   - in DevTools click "Svelte" tab
   [image: image.png]
   - reload http://localhost:5000
   [image: image.png]

**Comment by frederikhors** [comment] 2020-02-19 17:00
It's not because of you or related to you, @vfilatov.

**Comment by vfilatov** [comment] 2020-02-19 17:45
> Hi @vfilatov, are you running the sample locally? Or are you looking at the website docs.
> The docs use storybook library which uses React, etc that might confuse things or trigger errors

locally.

**Comment by bestguy** [comment] 2020-02-20 04:21
Thanks @vfilatov for the reproduction steps, can take a look

**Comment by vfilatov** [comment] 2020-02-24 20:09
node_modules/sveltestrap/src/Nav.svelte:
variable "fill" conflicts with Svelte DevTools
a workaround:
```git
diff --git a/Nav.svelte b/Nav.svelte
index f5493c9..247ff22 100644
--- a/Nav.svelte
+++ b/Nav.svelte
@@ -9,7 +9,7 @@
   export let vertical = false;
   export let horizontal = '';
   export let justified = false;
-  export let fill = false;
+  export let navfill = false;
   export let navbar = false;
   export let card = false;
 
@@ -35,7 +35,7 @@
       'nav-pills': pills,
       'card-header-pills': card && pills,
       'nav-justified': justified,
-      'nav-fill': fill
+      'nav-fill': navfill
     }
   );
 </script>
```

**Comment by bestguy** [comment] 2020-03-03 14:15
Thanks @vfilatov - we could change this, although would be a small breaking change.
Perhaps this is an issue we could fix in Svelte Devtools?  Any thoughts @RedHatter ?

**Comment by RedHatter** [comment] 2020-03-03 20:30
Thanks for the heads up. Shouldn't be a problem to fix. Just need to filter out native functions before I clone the local context.

**Comment by vfilatov** [comment] 2020-03-27 20:11
@RedHatter any chances to look at that issue? :)

**Comment by RedHatter** [comment] 2020-03-28 07:31
Thank you for the ping. Sorry I haven't looked into this sooner.

As far as I can tell this is fixed in svelte-devtools version 1.2.2. Can you verify? The latest version hasn't gone through review on chrome yet but you should be able to install on firefox. Make sure to use the latest svelte version.

**Comment by vfilatov** [comment] 2020-03-30 20:11
@RedHatter, thank you, I can confirm it is working on FireFox now.
Meanwhile it crashes under huge data set, but that might be a different story.

Thanks again!

**Comment by bestguy** [comment] 2020-10-19 16:04
Resolved in other repo, thanks.

**Closed by bestguy** 2020-10-19 16:04 UTC
