### ISSUE TITLE
TreeShaking

### ISSUE THREAD

**Issue by Froxz** [bestguy/sveltestrap#460] opened 2022-03-08 13:08 UTC
Hi,

I've noticed when importing:
```js
import { Accordion, AccordionItem } from 'sveltestrap'
```
actually pulls all components in the production build.

changing to, can't find any components:
```js
import Accordion from 'sveltestrap/Accordion'
import AccordionItem from 'sveltestrap/AccordionItem'
```

Workaround that worked:

```js
import Accordion from 'sveltestrap/src/Accordion'
import AccordionItem from 'sveltestrap/src/AccordionItem'
```

**Comment by demetrius-mp** [comment] 2022-03-09 22:54
duplicate of #362

**Closed** 2022-03-10 07:20 UTC

**Comment by siccovansas** [comment] 2022-03-22 17:30
Maybe this helps others. I had to import the components like this:
```
import Styles from 'sveltestrap/src/Styles.svelte';
import Container from 'sveltestrap/src/Container.svelte';
import Row from 'sveltestrap/src/Row.svelte';
```
