### ISSUE TITLE
Support SSR

### ISSUE THREAD

**Issue by CaptainN** [bestguy/sveltestrap#48] opened 2019-09-17 04:42 UTC
I have created a simple [Svelte starter for Meteor](https://github.com/CaptainN/meteor-svelte-starter), and it was reported that [`sveltestrap` doesn't work with my SSR solution](https://github.com/CaptainN/meteor-svelte-starter/issues/1). I believe this is because your component is published in a pre-compiled state, instead of providing raw source and exposing that through a `svelte` key in `package.json` as is demonstrated in [sveltejs/component-template](https://github.com/sveltejs/component-template).

Svelte's SSR support works by using an entirely different compiler for server rendering, and would seem to require raw source in order to function properly.

**Comment by bestguy** [comment] 2019-09-21 03:18
Thanks for the the heads up @CaptainN , will take a look at the Svelte 3 options.  I seem to remember a SSR option in Svelte or Rollup, will see if something can add there.  I'm reluctant to include source in npm tarballs but can do so if is the recommended approach.  Will look within next week.

**Comment by bestguy** [comment] 2019-09-21 15:16
I've published a beta version of `sveltestrap@3.1.2-0`, I will try out with your template as well.
PR is https://github.com/bestguy/sveltestrap/pull/50 and will merge after I can confirm this works.

**Comment by bestguy** [comment] 2019-09-22 02:41
Published fix in v3.2 (https://github.com/bestguy/sveltestrap/releases/tag/v3.2.0), I'll leave this open until one of us can confirm works with your template.

**Comment by bestguy** [comment] 2019-09-23 15:58
I tested out using your template and unfortunately this is same error:

```Error running template: Error: <Card> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules```

It looks like Svelte has a `generate: 'ssr'` option (https://svelte.dev/docs#svelte_compile), but it's really not clear to me how this is supposed to be packaged - issues seem to imply that you build a separate SSR bundle?  Ex: https://github.com/sveltejs/svelte/issues/196

I'll leave this issue open and will investigate.

**Comment by bestguy** [comment] 2019-09-23 16:10
Oh - actually this does work, however you must import the source directly @abigtoe, 

```javascript
import Card from 'sveltestrap/src/Card.svelte'
```

There is a "svelte" key in package.json, so unsure why the svelte SSR or template is not supporting this syntax:

```
import { Card } from 'sveltestrap';
```

I'll investigate if there is anything I can do in this library, but if not will close this week.

**Comment by abigtoe** [comment] 2019-10-01 14:21
@bestguy Confirmed, the direct import approach does work. Thanks.

**Comment by bestguy** [comment] 2019-10-01 14:22
Thanks!  I'll close this for now, I appreciate the heads up.

**Closed by bestguy** 2019-10-01 14:22 UTC

**Comment by larryosborn** [comment] 2019-10-01 18:12
This also works:
`import { Card } from 'sveltestrap/src';`

**Comment by CaptainN** [comment] 2019-10-02 05:26
Thanks @bestguy !
