### ISSUE TITLE
Modal error on close

### ISSUE THREAD

**Issue by ecentinela** [bestguy/sveltestrap#107] opened 2020-01-06 16:29 UTC
First of all, thank you for the package, it's being really helpful!

Now, I'm facing a problem with the modals.

I copy & pasted the demo in my app, but when I click on any of the buttons in order to close the modal the following error appears and the modal is not beging closed.

```
Uncaught (in promise) TypeError: Cannot read property 'c' of undefined
    at transition_out (index.mjs:697)
    at Object.o (App.svelte:4)
    at $s (sveltestrap.es.js:1)
    at Object.o (sveltestrap.es.js:1)
    at $s (sveltestrap.es.js:1)
    at Object.p (sveltestrap.es.js:1)
    at Object.p (sveltestrap.es.js:1)
    at ts (sveltestrap.es.js:1)
    at os (sveltestrap.es.js:1)
```

If I follow the error in chrome, I'm redirected directly to the following line:

```
outros.c.push(() => {
```

Anybody can help me with this, please?

Regards,

**Comment by bestguy** [comment] 2020-01-07 02:08
Hi @ecentinela , do you have any sample code or repo showing usage?  Are you using in a router, or sapper app, etc?

**Comment by ecentinela** [comment] 2020-01-07 13:37
Hi @bestguy!

You can use the demo (https://codesandbox.io/s/modern-cache-znqt3) from a previous ticket (https://github.com/bestguy/sveltestrap/issues/105) that is failing too.

If you open the modal and click the "cross" icon, you will see this in your console.

Hope it helps.

**Comment by frederikhors** [comment] 2020-01-07 14:24
@ecentinela the problem is just on codesandbox.

If you download the zip it works good.

No problem at all on this.

**Comment by ecentinela** [comment] 2020-01-07 21:24
Hi @frederikhors, @bestguy, here you have a demo with the error. Copy & pasted the demo like I said in my previous comment. Failing in local when I launch the project with "yarn watch".

[svelte.zip](https://github.com/bestguy/sveltestrap/files/4032514/svelte.zip)

Hope it helps.

**Comment by frederikhors** [comment] 2020-01-07 22:01
You're right. I'm using Rollup in my labs: everything ok. I think the problem is something bad w/ webpack.

**Comment by ecentinela** [comment] 2020-01-07 22:18
You are right! This is related with the webpack loader.

I was missing part of the configuration:

```
    alias: {
      svelte: path.resolve('node_modules', 'svelte')
    },
    mainFields: ['svelte', 'browser', 'module', 'main']
```

After adding these lines, it started to work! :)

Thanks!

**Comment by frederikhors** [comment] 2020-01-07 22:33
Can you close the issue please?

**Closed** 2020-01-07 23:07 UTC
