### ISSUE TITLE
Issue with svelte-select

### ISSUE THREAD

**Issue by Inqnuam** [bestguy/sveltestrap#436] opened 2022-01-27 09:19 UTC
Hello @bestguy,
Could you please check if[ this issue ](https://github.com/rob-balfre/svelte-select/issues/370)is coming from Svelstrap or svelte-select ?
Im unable to debug that

**Comment by bestguy** [comment] 2022-01-28 02:12
Hi @Inqnuam , would you mind adding a sample svelte repl that shows the issue?  Here's a starter:
 https://svelte.dev/repl/8ed6d1663e42490ea57b005cc12651f5?version=3.46.3

Happy to take a look at that.

**Comment by Inqnuam** [comment] 2022-01-28 09:44
> Hi @Inqnuam , would you mind adding a sample svelte repl that shows the issue? Here's a starter: https://svelte.dev/repl/8ed6d1663e42490ea57b005cc12651f5?version=3.46.3
> 
> Happy to take a look at that.

Here is https://svelte.dev/repl/c35098b1652d4e9b922ee9edb2efbc14?version=3.46.3

**Comment by Inqnuam** [comment] 2022-01-31 12:46
> Hi @Inqnuam , would you mind adding a sample svelte repl that shows the issue? Here's a starter: https://svelte.dev/repl/8ed6d1663e42490ea57b005cc12651f5?version=3.46.3
> 
> Happy to take a look at that.

Hello,
I have tried svelte-select inside an original Bootstrap Modal and svelte-select works as excepted.

**Comment by bestguy** [comment] 2022-02-03 21:26
Hi, since blur (tab to lose focus) works fine, I can only assume that svelte-select is adding a click handler to something not visible?  We don't do anything special here that would remove an event listener: https://github.com/bestguy/sveltestrap/blob/master/src/Modal.svelte

But happy to correct if you can point out or PR what the issue is in this library

**Comment by bestguy** [comment] 2022-02-15 03:39
Hi @Inqnuam , this looks to be fixed in sveltestrap@5.8.5:
https://svelte.dev/repl/c35098b1652d4e9b922ee9edb2efbc14?version=3.46.3

Thanks @tkieft for the fix here 👍

**Closed by bestguy** 2022-02-15 03:39 UTC

**Comment by Inqnuam** [comment] 2022-02-15 10:35
Awesome!
