### ISSUE TITLE
Icon.svelte causing crashing out

### ISSUE THREAD

**Issue by michaeljelly** [bestguy/sveltestrap#186] opened 2020-09-13 09:53 UTC
Hey, just seen you added icons to sveltestrap yesterday, but it seems to have crashed our builds.

Have you seen this? Any ideas on why that would be? Will revert back to previous version for now.

6:27:10 PM: node_modules/sveltestrap/src/Icon.svelte:10:4 - error TS2552: Cannot find name 'classes'. Did you mean 'class'?
6:27:10 PM: 10 $: classes = classnames(

Let me know if you need any more details.

**Comment by bestguy** [comment] 2020-09-13 20:27
Eee, sorry let me see what's up.

**Comment by bestguy** [comment] 2020-09-14 01:01
Hey @michaeljelly I'm unable to reproduce, tried with a Sapper app using Rollup. 
Could provide more info on your build and how you are including sveltestrap?  Are you using Icon?

The naming convention I used in Icon.svelte should be same as used in other places, e.g. Alert:
https://github.com/bestguy/sveltestrap/blob/master/src/Alert.svelte#L16

**Comment by michaeljelly** [comment] 2020-09-17 10:32
Interestingg. We weren't using Icon, which was why it was strange. Will see if it comes up again, atm we've just pinned the version.

It was specifically happening when our CI/CD auto-built the static app via using sapper export and deployed on a pipeline to Netlify.

**Comment by bestguy** [comment] 2020-09-18 01:22
Thanks, will try sapper export and see what's up.   Worse case I'll revert Icon if unstable.

**Comment by bestguy** [comment] 2020-09-28 03:50
Hi @michaeljelly we've reverted Icon addition for now.  We've removed in #190 and released as sveltestrap@3.9.0
We were using typescript in the component as well, so our build was currently not setup to handle this.

Thanks for the heads up.

**Comment by bestguy** [comment] 2020-10-03 13:47
Closing as assumed fixed

**Closed by bestguy** 2020-10-03 13:47 UTC
