### ISSUE TITLE
Bootstrap 5 (release) plus sveltestrap@5.0.0-beta.3-2 and CarouselIndicators

### ISSUE THREAD

**Issue by nstuyvesant** [bestguy/sveltestrap#272] opened 2021-05-07 20:15 UTC
Using SvelteKit, noticed the CarouselIndicators no longer appear now that I upgraded to sveltstrap@5.0.0-beta.3-2 and bootstrap@5.0.0.

Here's the code that worked with sveltstrap@4.2.1 and bootstrap@4.6.0:
```svelte
<script lang="ts">
  export const prerender = true
  import { Carousel, CarouselItem, CarouselIndicators } from 'sveltestrap/src' // per sveltstrap docs
  import items from './carousel.json'
  let activeIndex = 0
</script>

<template>
  <section>
    <Carousel {items} bind:activeIndex interval={7000}>
      <div class="carousel-inner">
        {#each items as item, index}
          <CarouselItem bind:activeIndex itemIndex={index}>
            <img src={item.url} class="d-block w-100" alt={item.description} />
          </CarouselItem>
        {/each}
        <CarouselIndicators bind:activeIndex {items} />
      </div>
    </Carousel>
  </section>
</template>
```

Looking at the source, I see the CarouselIndicators are rendered as an ordered list with `<li>` tags with a `style="active"` that moves from item to item as the slides change. But it should be rendering as buttons, right?

**Comment by bestguy** [comment] 2021-05-07 22:34
Thanks for the heads-up, I can duplicate issue locally in docs, will take a look.

**Comment by bestguy** [comment] 2021-05-07 22:38
The issue is Bootstrap's CSS selector now assumes `data-bs-target`: https://github.com/twbs/bootstrap/blob/main/scss/_carousel.scss#L173

A little weird as we don't need/use the `data-bs-*` stuff in Svelte, but looks like I can add easily.   Will fix with the v5.0.0 final this weekend.

**Comment by bestguy** [comment] 2021-05-14 03:11
Hi @nstuyvesant this should be resolved with https://github.com/bestguy/sveltestrap/releases/tag/v5.0.0

https://sveltestrap.js.org/?path=/story/components--carousel

Please let me know if you still see issues.

**Closed by bestguy** 2021-05-14 03:11 UTC

**Comment by nstuyvesant** [comment] 2021-05-14 15:02
Confirmed resolved - thanks!
