### ISSUE TITLE
Poppover broken with the latest sveltekit

### ISSUE THREAD

**Issue by lovasoa** [bestguy/sveltestrap#474] opened 2022-04-04 08:24 UTC
I opened an issue in sveltekit too: https://github.com/sveltejs/kit/issues/4504

The latest update of sveltekit breaks the poppover element from this repo.

**Comment by qbunt** [comment] 2022-04-05 21:35
Just got bit by this too, what's super odd is that I'm seeing references to components that I shouldn't be using. 

```
<script>
  import { Col, Container, Row } from 'sveltestrap'
</script>

<Container>
  <Row>
    <Col>
      <h2>hi</h2>
    </Col>
  </Row>
</Container>
```

I'm seeing 
```
import { popperGenerator, detectOverflow } from "./createPopper.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)

```

**Comment by nstuyvesant** [comment] 2022-04-06 17:33
This appears to be a duplicate of https://github.com/bestguy/sveltestrap/issues/463. If so, please close this issue and contribute to the other one.

**Closed** 2023-08-04 23:34 UTC
